2012/05/20 17:03:49 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in D:\xampp\yii\framework\web\CWebApplication.php:280
Stack trace:
#0 D:\xampp\yii\framework\web\CWebApplication.php(135): CWebApplication->runController('gii')
#1 D:\xampp\yii\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 D:\xampp\htdocs\news\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/news/index.php?r=gii
---
2012/05/20 17:36:08 [error] [exception.CException] exception 'CException' with message 'Property "User.salt" is not defined.' in D:\xampp\yii\framework\base\CComponent.php:131
Stack trace:
#0 D:\xampp\yii\framework\db\ar\CActiveRecord.php(144): CComponent->__get('salt')
#1 D:\xampp\htdocs\news\protected\models\User.php(103): CActiveRecord->__get('salt')
#2 D:\xampp\htdocs\news\protected\components\UserIdentity.php(41): User->validatePassword('3368807')
#3 D:\xampp\htdocs\news\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#4 D:\xampp\yii\framework\validators\CInlineValidator.php(43): LoginForm->authenticate('password', Array)
#5 D:\xampp\yii\framework\validators\CValidator.php(197): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#6 D:\xampp\yii\framework\base\CModel.php(158): CValidator->validate(Object(LoginForm), NULL)
#7 D:\xampp\htdocs\news\protected\controllers\SiteController.php(88): CModel->validate()
#8 D:\xampp\yii\framework\web\actions\CInlineAction.php(50): SiteController->actionLogin()
#9 D:\xampp\yii\framework\web\CController.php(309): CInlineAction->runWithParams(Array)
#10 D:\xampp\yii\framework\web\CController.php(287): CController->runAction(Object(CInlineAction))
#11 D:\xampp\yii\framework\web\CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 D:\xampp\yii\framework\web\CWebApplication.php(276): CController->run('login')
#13 D:\xampp\yii\framework\web\CWebApplication.php(135): CWebApplication->runController('site/login')
#14 D:\xampp\yii\framework\base\CApplication.php(162): CWebApplication->processRequest()
#15 D:\xampp\htdocs\news\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/news/index.php?r=site/login
HTTP_REFERER=http://localhost/news/index.php?r=site/login
---
2012/05/20 17:39:37 [error] [exception.CException] exception 'CException' with message 'Property "User.id" is not defined.' in D:\xampp\yii\framework\base\CComponent.php:131
Stack trace:
#0 D:\xampp\yii\framework\db\ar\CActiveRecord.php(144): CComponent->__get('id')
#1 D:\xampp\htdocs\news\protected\components\UserIdentity.php(45): CActiveRecord->__get('id')
#2 D:\xampp\htdocs\news\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#3 D:\xampp\yii\framework\validators\CInlineValidator.php(43): LoginForm->authenticate('password', Array)
#4 D:\xampp\yii\framework\validators\CValidator.php(197): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#5 D:\xampp\yii\framework\base\CModel.php(158): CValidator->validate(Object(LoginForm), NULL)
#6 D:\xampp\htdocs\news\protected\controllers\SiteController.php(88): CModel->validate()
#7 D:\xampp\yii\framework\web\actions\CInlineAction.php(50): SiteController->actionLogin()
#8 D:\xampp\yii\framework\web\CController.php(309): CInlineAction->runWithParams(Array)
#9 D:\xampp\yii\framework\web\CController.php(287): CController->runAction(Object(CInlineAction))
#10 D:\xampp\yii\framework\web\CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 D:\xampp\yii\framework\web\CWebApplication.php(276): CController->run('login')
#12 D:\xampp\yii\framework\web\CWebApplication.php(135): CWebApplication->runController('site/login')
#13 D:\xampp\yii\framework\base\CApplication.php(162): CWebApplication->processRequest()
#14 D:\xampp\htdocs\news\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/news/index.php?r=site/login
HTTP_REFERER=http://localhost/news/index.php?r=site/login
---
2012/05/20 17:39:53 [error] [exception.CException] exception 'CException' with message 'Property "User.id" is not defined.' in D:\xampp\yii\framework\base\CComponent.php:131
Stack trace:
#0 D:\xampp\yii\framework\db\ar\CActiveRecord.php(144): CComponent->__get('id')
#1 D:\xampp\htdocs\news\protected\components\UserIdentity.php(45): CActiveRecord->__get('id')
#2 D:\xampp\htdocs\news\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#3 D:\xampp\yii\framework\validators\CInlineValidator.php(43): LoginForm->authenticate('password', Array)
#4 D:\xampp\yii\framework\validators\CValidator.php(197): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#5 D:\xampp\yii\framework\base\CModel.php(158): CValidator->validate(Object(LoginForm), NULL)
#6 D:\xampp\htdocs\news\protected\controllers\SiteController.php(88): CModel->validate()
#7 D:\xampp\yii\framework\web\actions\CInlineAction.php(50): SiteController->actionLogin()
#8 D:\xampp\yii\framework\web\CController.php(309): CInlineAction->runWithParams(Array)
#9 D:\xampp\yii\framework\web\CController.php(287): CController->runAction(Object(CInlineAction))
#10 D:\xampp\yii\framework\web\CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 D:\xampp\yii\framework\web\CWebApplication.php(276): CController->run('login')
#12 D:\xampp\yii\framework\web\CWebApplication.php(135): CWebApplication->runController('site/login')
#13 D:\xampp\yii\framework\base\CApplication.php(162): CWebApplication->processRequest()
#14 D:\xampp\htdocs\news\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/news/index.php?r=site/login
HTTP_REFERER=http://localhost/news/index.php?r=site/login
---
